apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # Делаем приложение доступным извне