name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка JDK 21 для сборки Spring Boot
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    # Шаг 3: Сборка JAR-файла с помощью Maven
    - name: Build JAR with Maven
      run: mvn clean package -DskipTests  # создаёт target/demo-0.0.1-SNAPSHOT.jar

    # Шаг 4: Логин в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Шаг 5: Сборка Docker-образа
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:latest .

    # Шаг 6: Публикация Docker-образа
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:latest